services:
    upsnap:
        container_name: upsnap
        image: ghcr.io/seriousm4x/upsnap:latest
        network_mode: host
        restart: unless-stopped
        volumes:
            - /root/docker/upsnap-stack/upsnap/data:/app/pb_data
        environment:
            - TZ=America/New_York
            - UPSNAP_SCAN_RANGE=${UPSNAP_NETWORK_SCAN_RANGE}
        healthcheck:
            test: curl -fs "http://localhost:8090/api/health" || exit 1
            interval: 10s
